"""ASPB drift complaint PDF generator using reportlab."""
from io import BytesIO
from datetime import date as date_type

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def generate_complaint_pdf(report: dict, farmer_profile: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )
    styles = getSampleStyleSheet()
    center = ParagraphStyle("center", parent=styles["Heading1"], fontSize=14, alignment=1)
    h2 = styles["Heading2"]
    normal = styles["Normal"]
    story = []

    # Header
    story.append(Paragraph("AR STATE PLANT BOARD", center))
    story.append(Paragraph("DICAMBA DRIFT INCIDENT COMPLAINT", center))
    story.append(
        Paragraph(f"Generated: {date_type.today().strftime('%B %d, %Y')}", normal)
    )
    story.append(HRFlowable(width="100%", thickness=1))
    story.append(Spacer(1, 0.2 * inch))

    # 1 Complainant
    story.append(Paragraph("1. COMPLAINANT INFORMATION", h2))
    story.append(
        _table([
            ["Name:", farmer_profile.get("full_name") or "N/A"],
            ["County:", _county_name(report.get("county_fips", ""))],
            ["Email:", farmer_profile.get("email") or "N/A"],
        ])
    )
    story.append(Spacer(1, 0.2 * inch))

    # 2 Incident
    story.append(Paragraph("2. INCIDENT DETAILS", h2))
    story.append(
        _table([
            ["Incident Date:", str(report.get("incident_date") or "N/A")],
            ["Affected Crop:", report.get("affected_crop") or "N/A"],
            ["Estimated Acres:", str(report.get("affected_acres") or "N/A")],
            ["Suspected Herbicide:", report.get("suspected_herbicide") or "N/A"],
        ])
    )
    story.append(Spacer(1, 0.2 * inch))

    # 3 Weather
    story.append(Paragraph("3. WEATHER CONDITIONS AT TIME OF INCIDENT", h2))
    wx = report.get("weather_json") or {}
    summary = wx.get("hourly_summary", {}) if wx.get("available") else {}
    if summary:
        weather_rows = [
            ["Wind Speed:", f"{summary.get('wind_speed_mph_avg', 'N/A')} mph"],
            ["Wind Direction:", summary.get("wind_direction_label") or "N/A"],
            ["Temperature:", f"{summary.get('temp_f_at_noon', 'N/A')} °F"],
            ["Data Source:", "NOAA via Open-Meteo Archive API"],
        ]
    else:
        weather_rows = [["Note:", "Weather data unavailable for this incident date."]]
    story.append(_table(weather_rows))
    story.append(Spacer(1, 0.2 * inch))

    # 4 Symptoms
    story.append(Paragraph("4. SYMPTOM DESCRIPTION", h2))
    story.append(
        Paragraph(report.get("symptoms_description") or "No description provided.", normal)
    )
    story.append(Spacer(1, 0.2 * inch))

    # 5 Suspected source
    story.append(Paragraph("5. SUSPECTED SOURCE", h2))
    story.append(
        Paragraph(report.get("neighboring_applicator") or "Not specified.", normal)
    )
    story.append(Spacer(1, 0.2 * inch))

    # 6 Photo checklist
    story.append(Paragraph("6. PHOTO & DOCUMENTATION CHECKLIST", h2))
    for item in [
        "☐  Field damage photographs taken",
        "☐  GPS-tagged photos of affected area",
        "☐  Spray application records requested from applicator",
    ]:
        story.append(Paragraph(item, normal))
    story.append(Spacer(1, 0.2 * inch))

    # Footer
    story.append(HRFlowable(width="100%", thickness=1))
    story.append(Paragraph("SUBMIT THIS COMPLAINT TO:", h2))
    story.append(
        Paragraph("Email: arkansasstateplantboard@agriculture.arkansas.gov", normal)
    )
    story.append(
        Paragraph(
            "Mail: AR State Plant Board, 1 Natural Resources Dr, Little Rock, AR 72205",
            normal,
        )
    )
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph("Generated by AgroAdvisor AR", normal))

    doc.build(story)
    return buffer.getvalue()


def _table(data: list) -> Table:
    t = Table(data, colWidths=[2 * inch, 4 * inch])
    t.setStyle(
        TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    return t


def _county_name(fips: str) -> str:
    from utils.counties import get_county_info
    info = get_county_info(fips)
    return info["county_name"] if info else fips
